---
- hosts: oldubuntu
  become: true
  tasks:
  - name: systemctl for Apache2
    when: ansible_os_family == "Debian"
    service:
      name: apache2
      state: started
      enabled: yes
    ignore_errors: true

  - name: systemctl for HTTPD
    when: ansible_os_family == "RedHat"
    service:
      name: httpd
      state: started
      enabled: yes
    ignore_errors: true

  - name: systemctl for NGINX
    when: ansible_os_family == "Debian"
    service:
      name: nginx
      state: started
      enabled: yes
    ignore_errors: true



- hosts: oldubuntu
  become: true
  tasks:
  - name: Copy index.html
    when: ansible_os_family == "Debian"
    copy:
      src: ./index.html
      dest: /var/www/html
      mode: 0755
